version: '1.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./log_clear.log:/var/log/application.log  # Monter le fichier de logs
      # - ./application.log:/var/log/application.log  # Monter le fichier de logs
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  streamlit:
    image: streamlit_app
    build:
        context: ./app
        dockerfile: Dockerfile
    ports:
        - "8501:8501"
    # working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - elasticsearch
    networks:
      - elk-network


volumes:
  elasticsearch_data:

networks:
  elk-network: